version: '3'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: Graph
      POSTGRES_USER: GraphDBUser
      POSTGRES_PASSWORD: GR@p|-|D|3Us3rP@33w0rd
    volumes:
      - btc_db_data:/var/lib/postgres/data
    restart: unless-stopped
    expose:
      - "5432"
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  btc_db_data:
  redis_data: